# Generated by Django 4.0.5 on 2022-08-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10000)),
                ('job_title', models.CharField(max_length=10000)),
                ('Company_name', models.CharField(max_length=10000)),
                ('Summary', models.CharField(max_length=10000)),
                ('Location_Company', models.CharField(max_length=10000)),
                ('type', models.CharField(max_length=10000)),
            ],
        ),
    ]
