# Generated by Django 4.0.5 on 2022-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_label_jobs_job_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('url_product', models.URLField()),
                ('old_product_price', models.FloatField(blank=True)),
                ('product_price', models.FloatField(blank=True)),
                ('rating', models.CharField(blank=True, max_length=200)),
                ('produc_details', models.CharField(blank=True, max_length=200)),
                ('difference_price', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Maj', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('difference_price', '-created'),
            },
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
