# Generated by Django 4.0.5 on 2022-08-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('difference_price', 'created')},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='current_price',
        ),
    ]
